# Generated by Django 3.2.7 on 2021-09-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='notes',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=99.99),
            preserve_default=False,
        ),
    ]
